"""empty message

Revision ID: 4d3306a54347
Revises: eae46430d8f1
Create Date: 2026-01-31 18:14:22.047077

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d3306a54347'
down_revision = 'eae46430d8f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.drop_column('id')

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('media_type',
               existing_type=postgresql.ENUM('photo', 'video', 'gif', name='media_type_enum'),
               type_=sa.Enum('photo', 'video', 'gif', name='mediatype'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('media_type',
               existing_type=sa.Enum('photo', 'video', 'gif', name='mediatype'),
               type_=postgresql.ENUM('photo', 'video', 'gif', name='media_type_enum'),
               existing_nullable=False)

    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))

    # ### end Alembic commands ###
